name: Java CI with Gradle

on:
  push:
    paths:
      - '**.java'
      - '**.json'
      - 'gradle**'
      - 'build.gradle'
  # Makes it possible to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UnsuspiciousStew
        path: build/libs/

    - name: Read data from gradle.properties
      id: read_properties
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './gradle.properties'
        properties: 'minecraft_version mod_version'

    - name: Trim whitespace from mod version
      run: echo "MOD_VERSION=$(echo ${{ steps.read_properties.outputs.mod_version }} | tr -d '[:space:]')" >> $GITHUB_ENV

    - name: Release
      uses: "ThisTestUser/marvinpinto-action-automatic-releases@1.0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.read_properties.outputs.minecraft_version }}"
        prerelease: false
        title: "UnsuspiciousStew for ${{ steps.read_properties.outputs.minecraft_version }}"
        files: |
          build/libs/*
